"""add sales_rep_id to orders

Revision ID: 1ec21519a9b6
Revises: e739dcd6203c
Create Date: 2025-11-26 06:23:51.325587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec21519a9b6'
down_revision: Union[str, None] = 'e739dcd6203c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('orders', sa.Column('sales_rep_id', sa.Integer(), nullable=True))

    # Populate existing orders with sales representatives
    # This uses a subquery to find sales reps for each supplier
    op.execute("""
        UPDATE orders
        SET sales_rep_id = (
            SELECT COALESCE(
                -- First try: find a sales rep staff member
                (SELECT ss.user_id
                 FROM supplier_staff ss
                 JOIN users u ON ss.user_id = u.id
                 WHERE ss.supplier_id = orders.supplier_id
                   AND ss.staff_role ILIKE '%sales%'
                   AND u.is_active = true
                 LIMIT 1),
                -- Second try: any active staff member
                (SELECT ss.user_id
                 FROM supplier_staff ss
                 JOIN users u ON ss.user_id = u.id
                 WHERE ss.supplier_id = orders.supplier_id
                   AND u.is_active = true
                 LIMIT 1),
                -- Fallback: supplier owner
                (SELECT s.user_id
                 FROM suppliers s
                 JOIN users u ON s.user_id = u.id
                 WHERE s.id = orders.supplier_id
                   AND u.is_active = true
                 LIMIT 1)
            )
        )
        WHERE sales_rep_id IS NULL
    """)

    # Now make it non-nullable
    op.alter_column('orders', 'sales_rep_id', nullable=False)
    op.create_index(op.f('ix_orders_sales_rep_id'), 'orders', ['sales_rep_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['sales_rep_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_sales_rep_id'), table_name='orders')
    op.drop_column('orders', 'sales_rep_id')
    # ### end Alembic commands ###

