"""add_supplier_id_to_chat_sessions

Revision ID: 3c9aac1d990c
Revises: 4dbb2cebd981
Create Date: 2025-11-26 12:06:01.410159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9aac1d990c'
down_revision: Union[str, None] = '4dbb2cebd981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add supplier_id column as nullable first
    op.add_column('chat_sessions', sa.Column('supplier_id', sa.Integer(), nullable=True))

    # Populate supplier_id from sales_rep_id by finding the supplier for each sales rep
    # This handles existing data
    op.execute("""
        UPDATE chat_sessions cs
        SET supplier_id = (
            SELECT COALESCE(
                (SELECT supplier_id FROM supplier_staff WHERE user_id = cs.sales_rep_id LIMIT 1),
                (SELECT id FROM suppliers WHERE user_id = cs.sales_rep_id LIMIT 1)
            )
        )
        WHERE supplier_id IS NULL
    """)

    # Now make it non-nullable
    op.alter_column('chat_sessions', 'supplier_id', nullable=False)

    op.drop_constraint(op.f('uq_chat_sessions_consumer_sales_rep'), 'chat_sessions', type_='unique')
    op.create_index(op.f('ix_chat_sessions_supplier_id'), 'chat_sessions', ['supplier_id'], unique=False)
    op.create_unique_constraint('uq_chat_sessions_consumer_supplier', 'chat_sessions', ['consumer_id', 'supplier_id'])
    op.create_foreign_key(None, 'chat_sessions', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_entity'), table_name='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_entity'), 'notifications', ['entity_type', 'entity_id'], unique=False)
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint('uq_chat_sessions_consumer_supplier', 'chat_sessions', type_='unique')
    op.drop_index(op.f('ix_chat_sessions_supplier_id'), table_name='chat_sessions')
    op.create_unique_constraint(op.f('uq_chat_sessions_consumer_sales_rep'), 'chat_sessions', ['consumer_id', 'sales_rep_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('chat_sessions', 'supplier_id')
    # ### end Alembic commands ###

