"""Initial migration: create all tables

Revision ID: 4dbb2cebd981
Revises:
Create Date: 2025-11-17 11:49:05.103849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4dbb2cebd981'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop ENUM types if they exist (to ensure clean state)
    op.execute("DROP TYPE IF EXISTS linkstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS orderstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS complaintstatus CASCADE")

    # Create ENUM types using raw SQL (more reliable)
    op.execute(
        "CREATE TYPE linkstatus AS ENUM ('PENDING', 'ACCEPTED', 'DENIED', 'BLOCKED')")
    op.execute(
        "CREATE TYPE orderstatus AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED')")
    op.execute(
        "CREATE TYPE complaintstatus AS ENUM ('OPEN', 'ESCALATED', 'RESOLVED')")

    # Create ENUM objects for use in table definitions (with create_type=False to prevent auto-creation)
    linkstatus_enum = postgresql.ENUM(
        'PENDING', 'ACCEPTED', 'DENIED', 'BLOCKED', name='linkstatus', create_type=False)
    orderstatus_enum = postgresql.ENUM(
        'PENDING', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', name='orderstatus', create_type=False)
    complaintstatus_enum = postgresql.ENUM(
        'OPEN', 'ESCALATED', 'RESOLVED', name='complaintstatus', create_type=False)

    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password_hash', sa.String(
                        length=255), nullable=False),
                    sa.Column('role', sa.String(length=50), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('consumers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('organization_name', sa.String(
                        length=255), nullable=False),
                    # Base64 encoded image data
                    sa.Column('profile_image', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_consumers_user_id'),
                    'consumers', ['user_id'], unique=False)
    op.create_table('notifications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('recipient_id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=False),
                    sa.Column('entity_id', sa.Integer(), nullable=True),
                    sa.Column('entity_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['recipient_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_notifications_is_read'),
                    'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'),
                    'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'),
                    'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_entity', 'notifications',
                    ['entity_type', 'entity_id'], unique=False)
    op.create_table('suppliers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('company_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_suppliers_user_id'),
                    'suppliers', ['user_id'], unique=False)
    op.create_table('links',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('consumer_id', sa.Integer(), nullable=False),
                    sa.Column('supplier_id', sa.Integer(), nullable=False),
                    sa.Column('status', linkstatus_enum, nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['consumer_id'], ['consumers.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('consumer_id', 'supplier_id',
                                        name='uq_consumer_supplier')
                    )
    op.create_index(op.f('ix_links_consumer_id'), 'links',
                    ['consumer_id'], unique=False)
    op.create_index(op.f('ix_links_status'), 'links', ['status'], unique=False)
    op.create_index(op.f('ix_links_supplier_id'), 'links',
                    ['supplier_id'], unique=False)
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('supplier_id', sa.Integer(), nullable=False),
                    sa.Column('consumer_id', sa.Integer(), nullable=False),
                    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
                    sa.Column('status', orderstatus_enum, nullable=False),
                    sa.Column('total_kzt', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['consumer_id'], ['consumers.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['sales_rep_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_orders_consumer_id'),
                    'orders', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_orders_status'),
                    'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_supplier_id'),
                    'orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_orders_sales_rep_id'),
                    'orders', ['sales_rep_id'], unique=False)
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('supplier_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('price_kzt', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('currency', sa.String(length=3), nullable=False),
                    sa.Column('sku', sa.String(length=100), nullable=False),
                    sa.Column('stock_qty', sa.Integer(), nullable=False),
                    sa.Column('unit', sa.String(length=50), nullable=True),
                    sa.Column('min_order_qty', sa.Integer(), nullable=True),
                    sa.Column('discount_percent', sa.Numeric(
                        precision=5, scale=2), nullable=True),
                    sa.Column('lead_time_days', sa.Integer(), nullable=True),
                    sa.Column('delivery_available', sa.Boolean(),
                              nullable=False, server_default='true'),
                    sa.Column('pickup_available', sa.Boolean(),
                              nullable=False, server_default='true'),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_supplier_id'),
                    'products', ['supplier_id'], unique=False)
    op.create_table('supplier_staff',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('supplier_id', sa.Integer(), nullable=False),
                    sa.Column('staff_role', sa.String(
                        length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_supplier_staff_supplier_id'),
                    'supplier_staff', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_staff_user_id'),
                    'supplier_staff', ['user_id'], unique=False)
    op.create_table('chat_sessions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('consumer_id', sa.Integer(), nullable=False),
                    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['consumer_id'], ['consumers.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['sales_rep_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'consumer_id', 'sales_rep_id', name='uq_chat_sessions_consumer_sales_rep')
                    )
    op.create_index(op.f('ix_chat_sessions_consumer_id'),
                    'chat_sessions', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_sales_rep_id'),
                    'chat_sessions', ['sales_rep_id'], unique=False)
    op.create_table('complaints',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('consumer_id', sa.Integer(), nullable=False),
                    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
                    sa.Column('manager_id', sa.Integer(), nullable=False),
                    sa.Column('status', complaintstatus_enum, nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('resolution', sa.Text(), nullable=True),
                    sa.Column('consumer_feedback',
                              sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['consumer_id'], ['consumers.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['manager_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['orders.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['sales_rep_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_complaints_consumer_id'),
                    'complaints', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_complaints_manager_id'),
                    'complaints', ['manager_id'], unique=False)
    op.create_index(op.f('ix_complaints_order_id'),
                    'complaints', ['order_id'], unique=False)
    op.create_index(op.f('ix_complaints_sales_rep_id'),
                    'complaints', ['sales_rep_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'),
                    'complaints', ['status'], unique=False)
    op.create_table('order_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('qty', sa.Integer(), nullable=False),
                    sa.Column('unit_price_kzt', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['orders.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['products.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_order_items_order_id'),
                    'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'),
                    'order_items', ['product_id'], unique=False)
    op.create_table('chat_messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('session_id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('file_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['sender_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_chat_messages_sender_id'),
                    'chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'),
                    'chat_messages', ['session_id'], unique=False)
    op.create_table('chat_message_attachments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('message_id', sa.Integer(), nullable=False),
                    sa.Column('file_type', sa.String(length=50),
                              nullable=False),  # 'image', 'file', 'audio'
                    sa.Column('file_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('mime_type', sa.String(
                        length=100), nullable=True),
                    # Base64 encoded data
                    sa.Column('file_data', sa.Text(), nullable=False),
                    sa.Column('file_size', sa.Integer(),
                              nullable=True),  # Size in bytes
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_chat_message_attachments_message_id'),
                    'chat_message_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_message_attachments_message_id'),
                  table_name='chat_message_attachments')
    op.drop_table('chat_message_attachments')
    op.drop_index(op.f('ix_chat_messages_session_id'),
                  table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_sender_id'),
                  table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_sales_rep_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_order_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_manager_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_consumer_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_chat_sessions_sales_rep_id'),
                  table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_consumer_id'),
                  table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_supplier_staff_user_id'),
                  table_name='supplier_staff')
    op.drop_index(op.f('ix_supplier_staff_supplier_id'),
                  table_name='supplier_staff')
    op.drop_table('supplier_staff')
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_sales_rep_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_sales_rep_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_supplier_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_consumer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_links_supplier_id'), table_name='links')
    op.drop_index(op.f('ix_links_status'), table_name='links')
    op.drop_index(op.f('ix_links_consumer_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_suppliers_user_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_notifications_entity', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'),
                  table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_consumers_user_id'), table_name='consumers')
    op.drop_table('consumers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # Drop ENUM types (must be done after dropping tables that use them)
    op.execute("DROP TYPE IF EXISTS complaintstatus")
    op.execute("DROP TYPE IF EXISTS orderstatus")
    op.execute("DROP TYPE IF EXISTS linkstatus")
    # ### end Alembic commands ###
