"""add units to products

Revision ID: b7c34905fbfe
Revises: bba9666016ab
Create Date: 2025-11-23 21:26:38.071419

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7c34905fbfe"
down_revision: str | None = "bba9666016ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add nullable columns first
    op.add_column("products", sa.Column("unit", sa.String(length=50), nullable=True))
    op.add_column("products", sa.Column("min_order_qty", sa.Integer(), nullable=True))
    op.add_column(
        "products",
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column("products", sa.Column("lead_time_days", sa.Integer(), nullable=True))

    # Add NOT NULL columns with server_default for existing rows
    # This ensures existing products get default values (True) for these boolean fields
    op.add_column(
        "products",
        sa.Column(
            "delivery_available", sa.Boolean(), nullable=False, server_default="true"
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "pickup_available", sa.Boolean(), nullable=False, server_default="true"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "lead_time_days")
    op.drop_column("products", "pickup_available")
    op.drop_column("products", "delivery_available")
    op.drop_column("products", "discount_percent")
    op.drop_column("products", "min_order_qty")
    op.drop_column("products", "unit")
    # ### end Alembic commands ###
