"""add consumer_feedback to complaints

Revision ID: bba9666016ab
Revises: 7f08f45cce4d
Create Date: 2025-11-23 16:27:24.131986

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bba9666016ab"
down_revision: str | None = "7f08f45cce4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaints", sa.Column("consumer_feedback", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("complaints", "consumer_feedback")
    # ### end Alembic commands ###
