"""complaint finding salesperson

Revision ID: e739dcd6203c
Revises: b7c34905fbfe
Create Date: 2025-11-23 21:59:36.907195

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e739dcd6203c"
down_revision: str | None = "b7c34905fbfe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
